# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1/robomimic/dance:
  model_name: "model_133000.onnx"
  num_observations: 76
#   observations: ["ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions", "g1_mimic_phase"]
  observations: ["actions", "ang_vel", "dof_pos", "dof_vel", "gravity_vec", "g1_mimic_phase"]
  observations_history: [0, 1, 2, 3, 4]  # 0 is the latest observation
  observations_history_priority: "term"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0]
  rl_kp: [100, 100, 100, 150, 40, 40,
            100, 100, 100, 150, 40, 40,
            400, 400, 400,
            100,   100,  50, 50,
            100,   100,  50, 50] # policy计算力矩的pd
  rl_kd: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
            2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
            5.0, 5.0, 5.0,
            2.0, 2.0, 2.0, 2.0,
            2.0, 2.0, 2.0, 2.0]
  fixed_kp: [100, 100, 100, 150, 40, 40,
            100, 100, 100, 150, 40, 40,
            400, 400, 400,
            100,   100,  50, 50, 20, 20, 20,
            100,   100,  50, 50, 20, 20, 20] # 下发到实际的pd
  fixed_kd: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
            2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
            5.0, 5.0, 5.0,
            2.0, 2.0, 2.0, 2.0, 0.4, 0.4, 0.4,
            2.0, 2.0, 2.0, 2.0, 0.4, 0.4, 0.4]
  num_of_dofs: 23
  action_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [88.0, 88.0, 88.0, 139.0, 50.0, 50.0,
                  88.0, 88.0, 88.0, 139.0, 50.0, 50.0,
                  88.0, 50.0, 50.0,
                  25.0, 25.0, 25.0, 25.0,
                  25.0, 25.0, 25.0, 25.0]
  default_dof_pos: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                    0.0, 0.0, 0.0,
                    0.2, 0.2, 0.0, 0.9,
                    0.2, -0.2, 0.0, 0.9]
  joint_mapping: [0, 1, 2, 3, 4, 5, 
                6, 7, 8, 9, 10, 11, 
                12, 13, 14, 
                15, 16, 17, 18, 
                22, 23, 24, 25]
