# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1/robomimic/beyonddance:
  model_name: "policy_cdance_oldpd.onnx"
  num_observations: 154
  observations: ["commands_motion", "motion_anchor_ori_b", "ang_vel", "dof_pos", "dof_vel", "actions"]
  observations_history: []  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 1000
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0]

  rl_kp: [100, 100, 400, 100, 100, 400, 100, 100, 400, 150, 150, 100, 100,  40,  40, 100, 100,  40,  40,  50,  50,  50,  50,  20,  20,  20,  20,  20,  20]

  rl_kd: [2,   2,   5,   2,   2,   5,   2,   2,   5,   4,   4,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   0.4, 0.4, 0.4, 0.4, 0.4, 0.4]

  num_of_dofs: 29
  action_scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]

  wheel_indices: []
  lin_vel_scale: 1.0
  ang_vel_scale: 1.0
  dof_pos_scale: 1.0 
  dof_vel_scale: 1.0 
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [ 88.0,  88.0, 88.0,
                   88.0,  88.0, 88.0,
                   88.0,  88.0, 88.0,
                  139.0, 139.0      , 25.0, 25.0,
                   50.0,  50.0      , 25.0, 25.0,
                   50.0,  50.0      , 25.0, 25.0,
                                      25.0, 25.0,
                                       5.0,  5.0,
                                       5.0,  5.0,
                                       5.0,  5.0]
  default_dof_pos: [-0.312, -0.312, 0, 
                         0,      0, 0, 
                         0,      0, 0, 
                     0.669,  0.669, 0.2,  0.2, 
                    -0.363, -0.363, 0.2, -0.2, 
                         0,      0, 0,      0, 
                       0.6,    0.6, 
                         0,      0, 
                         0,      0, 
                         0,      0]

  joint_mapping: [0, 6, 12,
                  1, 7, 13,
                  2, 8, 14,
                  3, 9    , 15, 22,
                  4, 10   , 16, 23,
                  5, 11   , 17, 24,
                            18, 25,
                            19, 26,
                            20, 27,
                            21, 28]


