# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

g1/robomimic/beyonddance:
  model_name: "policy_mj.onnx"
  num_observations: 154
  observations: ["commands_motion", "motion_anchor_ori_b", "ang_vel", "dof_pos", "dof_vel", "actions"]
  observations_history: []  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 1000
  clip_actions_lower: [-100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                       -100.0, -100.0        , -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0,
                                               -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                       100.0, 100.0        , 100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0,
                                             100.0, 100.0]

  rl_kp: [40.179, 40.179, 40.179, 
          99.098, 99.098, 28.501, 
          40.179, 40.179, 28.501, 
          99.098, 99.098,         14.251, 14.251, 
          28.501, 28.501,         14.251, 14.251, 
          28.501, 28.501,         14.251, 14.251, 
                                  14.251, 14.251, 
                                  14.251, 14.251, 
                                  16.778, 16.778, 
                                  16.778, 16.778]

  rl_kd: [2.558, 2.558, 2.558, 
          6.309, 6.309, 1.814, 
          2.558, 2.558, 1.814, 
          6.309, 6.309,         0.907, 0.907, 
          1.814, 1.814,         0.907, 0.907, 
          1.814, 1.814,         0.907, 0.907, 
                                0.907, 0.907, 
                                0.907, 0.907, 
                                1.068, 1.068, 
                                1.068, 1.068]
  # rl_kp: [0.0, 0.0, 0.0, 
  #         0.0, 0.0, 0.0, 
  #         0.0, 0.0, 0.0, 
  #         0.0, 0.0,      0.0, 0.0, 
  #         0.0, 0.0,      0.0, 0.0, 
  #         0.0, 0.0,      0.0, 0.0, 
  #                        0.0, 0.0,      
  #                        0.0, 0.0, 
  #                        0.0, 0.0,      
  #                        0.0, 0.0  ]


  # rl_kd: [0.0, 0.0, 0.0, 
  #         0.0, 0.0, 0.0, 
  #         0.0, 0.0, 0.0, 
  #         0.0, 0.0,      0.0, 0.0, 
  #         0.0, 0.0,      0.0, 0.0, 
  #         0.0, 0.0,      0.0, 0.0, 
  #                        0.0, 0.0,      
  #                        0.0, 0.0, 
  #                        0.0, 0.0,      
  #                        0.0, 0.0  ]

  num_of_dofs: 29
  action_scale: [ 0.548, 0.548, 0.548, 
                  0.351, 0.351, 0.439, 
                  0.548, 0.548, 0.439, 
                  0.351, 0.351,         0.439, 0.439, 
                  0.439, 0.439,         0.439, 0.439, 
                  0.439, 0.439,         0.439, 0.439, 
                                        0.439, 0.439, 
                                        0.439, 0.439, 
                                        0.075, 0.075, 
                                        0.075, 0.075]

  wheel_indices: []
  lin_vel_scale: 1.0
  ang_vel_scale: 1.0
  dof_pos_scale: 1.0 
  dof_vel_scale: 1.0
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [ 88.0,  88.0, 88.0,
                   88.0,  88.0, 88.0,
                   88.0,  88.0, 88.0,
                  139.0, 139.0      , 25.0, 25.0,
                   50.0,  50.0      , 25.0, 25.0,
                   50.0,  50.0      , 25.0, 25.0,
                                      25.0, 25.0,
                                       5.0,  5.0,
                                       5.0,  5.0,
                                       5.0,  5.0]
  default_dof_pos: [-0.312, -0.312, 0, 
                         0,      0, 0, 
                         0,      0, 0, 
                     0.669,  0.669, 0.2,  0.2, 
                    -0.363, -0.363, 0.2, -0.2, 
                         0,      0, 0,      0, 
                       0.6,    0.6, 
                         0,      0, 
                         0,      0, 
                         0,      0]

  joint_mapping: [0, 6, 12,
                  1, 7, 13,
                  2, 8, 14,
                  3, 9    , 15, 22,
                  4, 10   , 16, 23,
                  5, 11   , 17, 24,
                            18, 25,
                            19, 26,
                            20, 27,
                            21, 28]


